export const LOGIN_POPUP = "LOGIN_POPUP";
export const COOKIE_BANNER = "COOKIE_BANNER";
export const TOGGLE_NAV_OVERLAY = "TOGGLE_NAV_OVERLAY";
export const SET_PASSED_COOKIE_MODAL = "SET_PASSED_COOKIE_MODAL";
export const SET_RETAIL_INVESTOR = "SET_RETAIL_INVESTOR";
export const SET_INSTITUTIONAL_INVESTOR = "SET_INSTITUTIONAL_INVESTOR";
export const INVESTMENT_PLAN_PROGRESS_BAR = "INVESTMENT_PLAN_PROGRESS_BAR";
export const INVESTMENT_PLAN_DATA = "INVESTMENT_PLAN_DATA";
// userSetting
export const USER_TOKEN = "USER_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
// dashboardSetting
export const DAYS_AREA = "DAYS_AREA";
export const MONTHS_AREA = "MONTHS_AREA";
export const YEARS_AREA = "YEARS_AREA";
